title: Open Liberty
email: alasdair@us.ibm.com
description: >
  Open Liberty is the most flexible server runtime available to Earth’s Java developers.
baseurl: ""
url: "https://openliberty.io"
twitter_username: openlibertyio
github_username:  NottyCode

asciidoctor:
  base_dir: :docdir
  safe: 0
  attributes:
    - icons=font
    - source-highlighter=coderay
    - coderay-css=style

minify_html: true

google_tag_manager: GTM-TKP3KJ7
#google_analytics: UA-104349928-1

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-asciidoc
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock
