title: Awesomesauce
email: ajlohr@us.ibm.com
description: >
  Awesomesauce delivers new and existing middleware tools to modernize your cloud journey.
baseurl: ""
url: "https://openliberty.io"
twitter_username: openlibertyio
github_username:  NottyCode

asciidoctor:
  base_dir: :docdir
  safe: 0
  attributes:
    - icons=font
    - source-highlighter=coderay
    - coderay-linenums-mode=inline
    - coderay-linenums=true
    - coderay-css=class
    - allow-uri-read

google_tag_manager: GTM-TKP3KJ7

markdown: kramdown

assets:
  compress:
    css: false
    js: false

env: production
minify_html: false

plugins:
  - jekyll-feed
  - jekyll-asciidoc
  - jekyll-assets
  - ol-asciidoc
  - octopress-minify-html
exclude:
  - vendor # TravisCI bundles all gems in the vendor directory on its build servers, which Jekyll will mistakenly read and explode on.
  - docs/templates
