language: ruby
rvm:
- 2.4.1

before_install:
  - sudo apt-get install python3-bs4 -y

script: >
    if [ $TRAVIS_BRANCH = "master" && $ROUTE = $SITE_QA_DOMAIN ]; then
      cp robots.txt src/main/content/robots.txt      
      env JEKYLL_ENV=production GUIDE_CLONE_BRANCH=$GUIDE_QA_BRANCH ./scripts/build_jekyll_maven.sh
    elif [ $ROUTE == $SITE_DRAFT_GUIDES_DOMAIN ]; then      
      env GUIDE_CLONE_BRANCH=$GUIDE_DEV_BRANCH ./scripts/build_jekyll_maven.sh
    elif [ $ROUTE == $SITE_DEV_DOMAIN ]; then      
      env GUIDE_CLONE_BRANCH=$GUIDE_DEV_BRANCH ./scripts/build_jekyll_maven.sh
    else
      ./scripts/build_jekyll_maven.sh
    fi

# branch whitelist
branches:
  only:
    - master
    - development

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: env ROUTE=$SITE_QA_DOMAIN ./.travis/cf-push.sh
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: env ROUTE=$SITE_DRAFT_GUIDES_DOMAIN ./.travis/cf-push.sh
  - provider: script
    skip_cleanup: true
    on:
      branch: development
    script: env ROUTE=$SITE_DEV_DOMAIN ./.travis/cf-push.sh