language: ruby
rvm:
- 2.4.1

before_install:
  - sudo apt-get install python3-bs4 -y

# Trigger a build for each environment
jobs:
  include:
    - env: ROUTE=$SITE_QA_DOMAIN GUIDE_CLONE_BRANCH=$GUIDE_QA_BRANCH JEKYLL_ENV=production
      if: branch = master
    - env: ROUTE=$SITE_DRAFT_GUIDES_DOMAIN GUIDE_CLONE_BRANCH=$GUIDE_DEV_BRANCH
      if: branch = master
    - env: ROUTE=$SITE_DEV_DOMAIN GUIDE_CLONE_BRANCH=$GUIDE_DEV_BRANCH
      if: branch = development
    # Build other branches besides master and development
    - if: branch != master  AND branch != development 

script: >
    if [ $TRAVIS_BRANCH = "master" && $ROUTE = $SITE_QA_DOMAIN ]; then
      cp robots.txt src/main/content/robots.txt      
      ./scripts/build_jekyll_maven.sh
    elif [ $TRAVIS_BRANCH = "master" && $ROUTE = $SITE_DRAFT_GUIDES_DOMAIN ]; then
      ./scripts/build_jekyll_maven.sh
    elif [ $TRAVIS_BRANCH = "development" && $ROUTE = $SITE_DEV_DOMAIN ]; then
      env GUIDE_CLONE_BRANCH=$GUIDE_DEV_BRANCH ./scripts/build_jekyll_maven.sh
    else
      ./scripts/build_jekyll_maven.sh
    fi

# branch whitelist
branches:
  only:
    - master
    - development

sudo: false # route your build to the container-based infrastructure for a faster build

# deploy only the specified build to each route
deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
      condition: $ROUTE = $SITE_QA_DOMAIN
    script: ./.travis/cf-push.sh
  - provider: script
    skip_cleanup: true
    on:
      branch: master
      condition: $ROUTE = $SITE_DRAFT_GUIDES_DOMAIN
    script: ./.travis/cf-push.sh
  - provider: script
    skip_cleanup: true
    on:
      branch: development
      condition: $ROUTE = $SITE_DEV_DOMAIN
    script: ./.travis/cf-push.sh
