language: ruby
rvm:
- 2.4.1

before_install:
  - sudo apt-get install python3-bs4 -y

before_script:
- chmod +x ./scripts/build_jekyll_maven.sh # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./scripts/build_jekyll_maven.sh

# branch whitelist
branches:
  only:
    - master
    - development
    - multiPane

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  - provider: script
    on:
      branch: master
    script: env ROUTE=qa-guides.mybluemix.net JEKYLL_ENV=production ./.travis/cf-push.sh
  - provider: script
    on:
      branch: development
    script: env ROUTE=qa-guides-draft.mybluemix.net ./.travis/cf-push.sh
  - provider: script
    on:
      branch: multiPane
    script: env ROUTE=qa-guides-multipane.mybluemix.net ./.travis/cf-push.sh